// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-KAXqCxZivkfNBi1dDc4tLl17zLW4hOQ',
    appId: '1:26524622311:web:d45e6fb4bd4347bde8b142',
    messagingSenderId: '26524622311',
    projectId: 'jarnama-app-c2623',
    authDomain: 'jarnama-app-c2623.firebaseapp.com',
    storageBucket: 'jarnama-app-c2623.appspot.com',
    measurementId: 'G-VMTC1P0T4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBvcoQioYb4YuPvkHpSTkpomyjE-fRL-U',
    appId: '1:26524622311:android:2a7c2c48e8d84103e8b142',
    messagingSenderId: '26524622311',
    projectId: 'jarnama-app-c2623',
    storageBucket: 'jarnama-app-c2623.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvG1sgJe0kf4g_0XXQwRTIAkbJjxxERvc',
    appId: '1:26524622311:ios:627a1782e50b7463e8b142',
    messagingSenderId: '26524622311',
    projectId: 'jarnama-app-c2623',
    storageBucket: 'jarnama-app-c2623.appspot.com',
    iosClientId: '26524622311-dm6f93ggm6efsuectebq9vkvbjmi9v89.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnamaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvG1sgJe0kf4g_0XXQwRTIAkbJjxxERvc',
    appId: '1:26524622311:ios:627a1782e50b7463e8b142',
    messagingSenderId: '26524622311',
    projectId: 'jarnama-app-c2623',
    storageBucket: 'jarnama-app-c2623.appspot.com',
    iosClientId: '26524622311-dm6f93ggm6efsuectebq9vkvbjmi9v89.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnamaApp',
  );
}
